// This file has been automatically generated by genstub
#include <assert.h>
#include <string.h>
#include "py/dynruntime.h"
// ESP-IDF imports
#include <esp_err.h>
#include <esp_wifi.h>

STATIC mp_obj_t espidf_esp_err_to_name(mp_obj_t arg0) {
	// convert arg0
	uint val0 = (uint)mp_obj_get_int(arg0);
	// call
	const char* ret = esp_err_to_name(val0);
	return ret ? mp_obj_new_str(ret, strlen(ret)) : mp_const_none;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(espidf_esp_err_to_name_obj, espidf_esp_err_to_name);

// returns status code
STATIC mp_obj_t espidf_esp_wifi_set_ps(mp_obj_t arg0) {
	uint val0 = (uint)mp_obj_get_int(arg0);
	const uint ret = esp_wifi_set_ps(val0);
	return mp_obj_new_int(ret);
}
STATIC MP_DEFINE_CONST_FUN_OBJ_1(espidf_esp_wifi_set_ps_obj, espidf_esp_wifi_set_ps);


// returns 2-tuple of status, ps_mode
STATIC mp_obj_t espidf_esp_wifi_get_ps() {
        uint ps_mode = 0;
        const uint ret = esp_wifi_get_ps(&ps_mode);
        mp_obj_t pair_o = mp_obj_new_tuple(2, NULL);
        mp_obj_tuple_t *pair = MP_OBJ_TO_PTR(pair_o);
        pair->items[0] = mp_obj_new_int(ret);
        pair->items[1] = mp_obj_new_int(ps_mode);
	return pair_o;
}
STATIC MP_DEFINE_CONST_FUN_OBJ_0(espidf_esp_wifi_get_ps_obj, espidf_esp_wifi_get_ps);

mp_obj_t mpy_init(mp_obj_fun_bc_t *self, size_t n_args, size_t n_kw, mp_obj_t *args) {
	MP_DYNRUNTIME_INIT_ENTRY
	mp_store_global(MP_QSTR_esp_err_to_name, MP_OBJ_FROM_PTR(&espidf_esp_err_to_name_obj));
	mp_store_global(MP_QSTR_esp_wifi_get_ps, MP_OBJ_FROM_PTR(&espidf_esp_wifi_get_ps_obj));
	mp_store_global(MP_QSTR_esp_wifi_set_ps, MP_OBJ_FROM_PTR(&espidf_esp_wifi_get_ps_obj));
	MP_DYNRUNTIME_INIT_EXIT
}
